### ISSUE TITLE
Is it possible to not use evil module 

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#18]
Hello 
Is it possible to disable evil module

**Comment by DiamondBond** [comment]
Hi! :)

To disable evil you have to currently comment out the entire source code block, I know its not a nice solution but I will convert the evil package to a module soon for easy disabling, I will tag you in the commit.

In the future (after I implement this functionality) all you will have to do is comment/delete or add :tangle no: to the load evil module section in userconfig.org.

**Comment by DiamondBond** [comment]
https://github.com/DiamondBond/emacs/blob/master/userconfig.org#evil

Remove/comment this block and evil should not be loaded :)

**Comment by ghost** [comment]
Everything works
On startup I have a split window,left buffer is scratch buffer and right
buffer is the dashboard

How to let dashboard be the startup page ?

**Comment by DiamondBond** [comment]
Strange, initial-buffer should be set to dashboard, I just tried with a fresh clone and it works as intended.
![fresh](https://user-images.githubusercontent.com/5003374/170742756-14b9ab7a-5643-4143-b753-e3cb727ef8cc.png)

Have you retangled the config files with [./tangle.sh](https://github.com/DiamondBond/emacs/blob/master/tangle.sh) ?

Also consider updating the config as I have pushed a lot of fixes to the repo.

This snippet here within =dashboard= use-package declaration should be setting the initial buffer to dashboard and there shouldn't be a scratch buffer:
```
(setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
```

**Comment by ghost** [comment]
Thank you, when I get back home from work I will try, at work we use
windows :(
You have an amazing config, thanks for sharing your work

**Comment by DiamondBond** [comment]
Do you have access to WSL2 at work? If so it should theoretically be possible to run this configuration without too many issues.

I hope to be able to run this emacs configuration or at least a subset of it on Windows one day despite how much I despise Windows - there is a time and place for it.

Thank you very much for the kind words of encouragement, have a great day! :)

**Comment by ghost** [comment]
I tried with the lates Diamond Emacs, and I get split screen on startup

**Comment by DiamondBond** [comment]
That's really strange.

Please make a backup of your current `~/.emacs.d`:
```
cp -r ~/.emacs.d ~/.emacs.d.old
``` 
Then run this command to reset to head:
```
git fetch && git reset --hard origin/master && git clean -fd
```
Start Emacs and it should now work I hope.

If not proceed to run `M-x straight-thaw-versions` to sync to the locked package versions and then retangle & restart emacs daemon.

I hope this helps.

**Comment by ghost** [comment]
I don't want to take more your time, It did not work, maybe because I had
this error
$ cd /home/perrierjouet/.emacs.d/straight/repos/mu/
$ ./autogen.sh

*** meson build setup
/usr/bin/meson
*** Now run 'ninja -C build' to build mu
*** Or check the Makefile for some useful targets
Directory does not contain a valid build tree:
/home/perrierjouet/.emacs.d/straight/repos/mu/build

[Return code: 0]

$ cd /home/perrierjouet/.emacs.d/straight/repos/mu/
$ make

ninja -C /home/perrierjouet/.emacs.d/straight/repos/mu/build
ninja: Entering directory
`/home/perrierjouet/.emacs.d/straight/repos/mu/build'
ninja: error: loading 'build.ninja': No such file or directory
make: *** [Makefile:36: all] Error 1

[Return code: 2]

I installed all packages that got me errors, I have already mu installed
with my package manager sudo xbps-install mu

Thanks a lot for your time

**Comment by DiamondBond** [comment]
Try running `M-x mu-setup/automagic`

Edit
I Just noticed you mentioned this

> I have already mu installed
> with my package manager sudo xbps-install mu

This auto installs mu under the straight build dir as 'mu', I should mentioned this somewhere in the mail.org file I guess.

There is no need to use mu via xbps.

**Comment by ghost** [comment]
I have 2fa enabled on gmail

M-x mu-setup/automagic gives error

cd ~/.emacs.d/straight/repos/mu; ./autogen.sh; ninja -C build: exited
abnormally with code 1.
~/.emacs.d/straight/repos/mu/build/mu/mu init --maildir=~/Maildir
***@***.***: exited abnormally with code 127.
~/.emacs.d/straight/repos/mu/build/mu/mu index: exited abnormally with code
127.

**Comment by DiamondBond** [comment]
> I have 2fa enabled on gmail

You need to store your gmail app password in ~/.authinfo.gpg
https://support.google.com/accounts/answer/185833?hl=en

Useful gist: https://gist.github.com/kidd/3881298

Edit
Could you share a list of packages you had to install in order to get this up and running? I'd like to add it to the documentation for future newcomers if that's alright with you.

**Comment by ghost** [comment]
from the command line mu works
 mu index
indexing maildir /home/perrierjouet/Maildir -> store
/home/perrierjouet/.cache/mu/xapian
- indexing messages; processed: 4840; updated/new: 4840; cleaned-up: 0

with emacs I have this error
ninja -C /home/perrierjouet/.emacs.d/straight/repos/mu/build
ninja: Entering directory
`/home/perrierjouet/.emacs.d/straight/repos/mu/build'
ninja: error: loading 'build.ninja': No such file or directory
make: *** [Makefile:42: all] Error 1

I included a little video, you can see it's split the window on startup

**Comment by DiamondBond** [comment]
if it works from the command line that means system wide mu is being used, remove system mu package and let straight.el handle it for you.

delete the ~/.emacs.d/straight/repos/mu & ~/.emacs.d/straight/build/mu and run `M-x mu-setup/automagic` to compile and setup from scratch, make sure you edit the `mu-setup/init-mu` function in mail.org to have your maildir & mail address. 

mu binary should be called like this:
```
~/.emacs.d/straight/repos/mu/build/mu/mu 
```

> I included a little video, you can see it's split the window on startup
Could you attach or send a link to the video?

**Comment by ghost** [comment]
the problem is with the build, when I update config/update at the end, mu
never build with the error I shoed earlier,

~/.emacs.d/straight/repos/mu/build/mu/mu index

no such file or directory
~/.emacs.d/straight/repos/mu/build/mu/mu

since I already installed mu with my package manager, what should be
another solution ?

**Comment by DiamondBond** [comment]
You can try editing the use-package declaration for mu4e to utilize your package managers version of mu.

> In the use-package macro put ensure nil and install the package from your package manager.

Relevant issue: https://github.com/radian-software/straight.el/issues/491

Useful site: http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/

Another useful site: https://f-santos.gitlab.io/2020-04-24-mu4e.html

Useful reddit thread: https://www.reddit.com/r/emacs/comments/luktxr/emacs_is_trying_without_success_to_install_mu4e/

**Comment by ghost** [comment]
The perseverance was worthed :)
to build mu,
I cloned the repo
cd ninja

./configure.py --bootstrap
cmake -Bbuild-cmake
cmake --build build-cmake

cp -R * .emacs.d/straight/repos/mu/build/

now on startup emacs is starting with the dashboard only :)

**Comment by ghost** [comment]
I forgot to mention not to copy the build folder inside ninja clone,
in case some else has the same issue
I followed this help
https://github.com/ninja-build/ninja/issues/1463#issuecomment-1119514124

**Comment by DiamondBond** [comment]
I'm really glad you figured this out! :)
