### ISSUE TITLE
pdf-tools on voidlinux

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#19]
Hello, I am on voidlinux I have this 

-*- mode: compilation; default-directory: "~/.emacs.d/straight/build/pdf-tools/build/server/" -*-
Comint started at Fri May 27 04:04:13

/home/perrierjouet/.emacs.d/straight/build/pdf-tools/build/server/autobuild -i /home/perrierjouet/.emacs.d/straight/build/pdf-tools/
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling
---------------------------
No such program: autoreconf

**Comment by DiamondBond** [comment]
Hi!

It looks like autoreconf is missing, could you try installing it from the void repos?

**Comment by ghost** [comment]
autoconf install worked

**Comment by DiamondBond** [comment]
Just leaving this here for posterity's sake:
https://voidlinux.pkgs.org/current/voidlinux-main-aarch64/autoconf-2.69_9.aarch64.xbps.html
