### ISSUE TITLE
Mail module is not building at all,  is it possible to adapt the mail module with dependencies to install by the user and add configure the mu4e part only

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#21]
Sorry to disturb, since it's a great config, I tried desperately to make mu build it does not build at all

**Comment by DiamondBond** [comment]
Yes we probably can, I need to learn how to source vars from elisp into those exported things. If you know how to please make a pr! :)

Otherwise I will try get around to this as soon as is possible

**Comment by ghost** [comment]
Asking another question
