### ISSUE TITLE
mu fails to setup properly

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#22]

**Comment by ghost** [comment]
~/.emacs.d/straight/repos/mu/build/mu/mu init --maildir=~/mail/ --my-address=dagnachewa@gmail.com: exited abnormally with code 127.
Invalid face reference: quote [56 times]
cd ~/.emacs.d/straight/repos/mu; ./autogen.sh; ninja -C build: finished.
~/.emacs.d/straight/repos/mu/build/mu/mu init --maildir=~/mail/ --my-address=dagnachewa@gmail.com: exited abnormally with code 127.
Invalid face reference: quote [32 times]
~/.emacs.d/straight/repos/mu/build/mu/mu index: exited abnormally with code 127.
Invalid face reference: quote [24 times]
Quit

**Comment by DiamondBond** [comment]
I just setup this Emacs config on a fresh kubuntu 22.04 install on my new desktop.

I had issues with mu/mu4e initially but the key to setting up mu/mu4e is to have the dependencies installed via your package manager then let straight.el build it for you, after build and install is complete or even if it failed I just run the following command in Emacs: `mu-setup/automagic` and then it works.

**Comment by ghost** [comment]
Is it possible to use system mu ?
I tried many times, mu does not build

**Comment by ghost** [comment]
Finaly I gave up on mail the email config that worked for me, I consulted my gmail with this config
https://github.com/MatthewZMD/.emacs.d/blob/master/elisp/init-mu4e.el
Thank you for your time

**Comment by ghost** [comment]
Finaly I got mu4e work by using system mu mail.org

my mail.org function section 
https://github.com/wereket/emacs/blob/master/modules/mail.org#functions

![image](https://user-images.githubusercontent.com/89839215/172024132-72e92fa8-53fd-422f-8ab0-987bea1fed27.png)
![image](https://user-images.githubusercontent.com/89839215/172024140-bf3220b6-787b-4ccd-bc5a-231e8f9b3d9c.png)
