### ISSUE TITLE
Mail module is not building at all, is it possible to adapt the mail module with dependencies to install by the user and add configure the mu4e part only

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#23]
Hello,
On my voidlinux the function mu-setup/build-mu-binary exits with error code, mu never gets build. I tried manualy and automaticaly.
I had a working mu4e setting but on update it does not found mu4e.

Is it possible to make the mail module give option to install mu from the linux distro package manager as a second option ?. sorry my english

**Comment by DiamondBond** [comment]
I will look into making a package manager agnostic mu setup, I do not have much free time irl these days but when I do find some time I will try to look into this and your other PR regarding mail setup sourcing variables from globals.org.

**Comment by ghost** [comment]
After installing gmime-devel from my voidlinux package manager, mu builds.
