### ISSUE TITLE
[MAIL] I tried mbsync and it does not work

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#26]
https://github.com/wereket/emacs/blob/master/modules/mail.org#mbsyncrc

on startup I got error

Loading /home/perrierjouet/.emacs.d/config.el (source)...
Loading /home/perrierjouet/.emacs.d/globals.el (source)...done
Function provided is already compiled [8 times]
Loading /home/perrierjouet/.emacs.d/config.el (source)...done
Loading /home/perrierjouet/.emacs.d/userconfig.el (source)...
Loading /home/perrierjouet/.emacs.d/modules/reddit.el (source)...done
Loading /home/perrierjouet/.emacs.d/modules/discord.el (source)...done
Loading /home/perrierjouet/.emacs.d/modules/mail.el (source)...done
Loading /home/perrierjouet/.emacs.d/userconfig.el (source)...done
Turning on magit-auto-revert-mode...done
[yas] Prepared just-in-time loading of snippets successfully.
For information about GNU Emacs and the GNU system, type C-h C-a.
Invalid face reference: quote [32 times]
Package cl is deprecated
error in process sentinel: mu4e--server-sentinel: Mu server process ended with exit code 1
error in process sentinel: Mu server process ended with exit code 1
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
Invalid face reference: quote [16 times]
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead. [3 times]
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘return’ is an obsolete alias (as of 27.1); use ‘cl-return’ instead.
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead. [2 times]
Invalid face reference: quote [8 times]
Created mpv link.
Invalid face reference: quote [24 times]

**Comment by DiamondBond** [comment]
Have you tried @miguelmorin 's solution here: https://github.com/djcb/mu/issues/1316

```
mu init
mu find hello
mu index
```
